apiVersion: v1
kind: ServiceAccount
metadata:
  name: boundary-controller
  namespace: {{ include "boundary.namespace" . }}
  labels:
    app.kubernetes.io/name: boundary-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  {{- if .Values.controller.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.controller.serviceAccount.annotations | nindent 4 }}
  {{- end }}
