apiVersion: v1
kind: Service
metadata:
  name: boundary-controller-internal
  namespace: {{ include "boundary.namespace" . }}
  labels:
    app.kubernetes.io/name: boundary-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
spec:
  type: ClusterIP
  clusterIP: None
  ports:
  - port: 9200
    targetPort: api
    protocol: TCP
    name: api
  - port: 9201
    targetPort: cluster
    protocol: TCP
    name: cluster
  publishNotReadyAddresses: true
  selector:
    app.kubernetes.io/name: boundary-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
