apiVersion: v1
kind: Service
metadata:
  name: boundary-controller
  namespace: {{ include "boundary.namespace" . }}
  labels:
    app.kubernetes.io/name: boundary-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  {{- if .Values.controller.service.annotations }}
  annotations:
    {{- toYaml .Values.controller.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - port: 9200
    targetPort: api
    protocol: TCP
    name: api
  - port: 9201
    targetPort: cluster
    protocol: TCP
    name: cluster
  selector:
    app.kubernetes.io/name: boundary-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
