apiVersion: v1
kind: ServiceAccount
metadata:
  name: boundary-worker
  namespace: {{ include "boundary.namespace" . }}
  labels:
    app.kubernetes.io/name: boundary-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
{{- if .Values.worker.serviceAccount.annotations }}
  annotations:
    {{- toYaml .Values.worker.serviceAccount.annotations | nindent 4 }}
{{- end }}
