apiVersion: v1
kind: Service
metadata:
  name: boundary-worker
  namespace: {{ include "boundary.namespace" . }}
  labels:
    app.kubernetes.io/name: boundary-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    helm.sh/chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
  {{- if .Values.worker.service.annotations }}
  annotations:
    {{- toYaml .Values.worker.service.annotations | nindent 4 }}
  {{- end }}
spec:
  type: ClusterIP
  ports:
  - port: 9202
    targetPort: proxy
    protocol: TCP
    name: proxy
  selector:
    app.kubernetes.io/name: boundary-worker
    app.kubernetes.io/instance: {{ .Release.Name }}
